[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.14.0"
nfd = "0.0.4"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
native-dialog = "0.6.3"
docx = "1.1.2"
chrono = "0.4.19"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"